package com.fadhly.gestura

object SignLanguages {
    val signLanguageList = listOf(
        SignDataClass(
            "A",
            R.drawable.gesture_a
        ),
        SignDataClass(
            "B",
            R.drawable.gesture_b
        ),
        SignDataClass(
            "C",
            R.drawable.gesture_c
        ),
        SignDataClass(
            "D",
            R.drawable.gesture_d
        ),
        SignDataClass(
            "E",
            R.drawable.gesture_e
        ),
        SignDataClass(
            "F",
            R.drawable.gesture_f
        ),
        SignDataClass(
            "G",
            R.drawable.gesture_g
        ),
        SignDataClass(
            "H",
            R.drawable.gesture_h
        ),
        SignDataClass(
            "I",
            R.drawable.gesture_i
        ),
        SignDataClass(
            "J",
            R.drawable.gesture_j
        ),
        SignDataClass(
            "K",
            R.drawable.gesture_k
        ),
        SignDataClass(
            "L",
            R.drawable.gesture_l
        ),
        SignDataClass(
            "M",
            R.drawable.gesture_m
        ),
        SignDataClass(
            "N",
            R.drawable.gesture_n
        ),
        SignDataClass(
            "O",
            R.drawable.gesture_o
        ),
        SignDataClass(
            "P",
            R.drawable.gesture_p
        ),
        SignDataClass(
            "Q",
            R.drawable.gesture_q
        ),
        SignDataClass(
            "R",
            R.drawable.gesture_r
        ),
        SignDataClass(
            "S",
            R.drawable.gesture_s
        ),
        SignDataClass(
            "T",
            R.drawable.gesture_t
        ),
        SignDataClass(
            "U",
            R.drawable.gesture_u
        ),
        SignDataClass(
            "V",
            R.drawable.gesture_v
        ),
        SignDataClass(
            "W",
            R.drawable.gesture_w
        ),
        SignDataClass(
            "X",
            R.drawable.gesture_x
        ),
        SignDataClass(
            "Y",
            R.drawable.gesture_y
        ),
        SignDataClass(
            "Z",
            R.drawable.gesture_z
        )
    )
}